import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1769999999999 implements MigrationInterface {
    name = 'InitialSchema1769999999999'

    public async up(queryRunner: QueryRunner): Promise<void> {
        if (await queryRunner.hasTable("users")) {
            return;
        }
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"`);
        await queryRunner.query(`CREATE TYPE "organization_members_role_enum" AS ENUM('OWNER', 'ADMIN', 'MEMBER')`);
        await queryRunner.query(`CREATE TABLE "organization_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "userId" uuid NOT NULL, "role" "organization_members_role_enum" NOT NULL DEFAULT 'MEMBER', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7c48546e8026fb043d9ad0c2c8c" UNIQUE ("organizationId", "userId"), CONSTRAINT "PK_c2b39d5d072886a4d9c8105eb9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5652c2c6b066835b6c500d0d83" ON "organization_members" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e826222ad017663c6db1a45a4f" ON "organization_members" ("userId") `);
        await queryRunner.query(`CREATE TYPE "invites_role_enum" AS ENUM('OWNER', 'ADMIN', 'MEMBER')`);
        await queryRunner.query(`CREATE TABLE "invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "email" character varying NOT NULL, "role" "invites_role_enum" NOT NULL DEFAULT 'MEMBER', "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "acceptedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_18a9a6c85f7cc6f42ebef3b3188" UNIQUE ("token"), CONSTRAINT "PK_aa52e96b44a714372f4dd31a0af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_18a9a6c85f7cc6f42ebef3b318" ON "invites" ("token") `);
        await queryRunner.query(`CREATE TYPE "organizations_plan_enum" AS ENUM('STARTER', 'PRO', 'BUSINESS')`);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "plan" "organizations_plan_enum" NOT NULL DEFAULT 'STARTER', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "users_role_enum" AS ENUM('super_admin', 'tenant_admin', 'accountant', 'user')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "role" "users_role_enum" NOT NULL DEFAULT 'user', "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP, "lastLoginTimeZone" character varying, "lastLoginUtcOffsetMinutes" integer, "deletionRequestedAt" TIMESTAMP, "isPendingDeletion" boolean NOT NULL DEFAULT false, "twoFactorSecret" character varying, "twoFactorEnabled" boolean NOT NULL DEFAULT false, "twoFactorBackupCodes" text array, "twoFactorEnabledAt" TIMESTAMP, "isEmailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "emailVerificationSentAt" TIMESTAMP WITH TIME ZONE, "emailVerifiedAt" TIMESTAMP WITH TIME ZONE, "passwordResetToken" character varying, "passwordResetExpiresAt" TIMESTAMP WITH TIME ZONE, "tenantId" uuid NOT NULL, "currentOrgId" uuid, "removedFromTenantAt" TIMESTAMP WITH TIME ZONE, "removedFromTenantBy" uuid, "removedFromTenantReason" character varying, "removedFromTenantId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tokenVersion" integer NOT NULL DEFAULT '0', "notificationPreferences" text, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "tenants_subscriptionplan_enum" AS ENUM('free', 'basic', 'professional', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "tenants_status_enum" AS ENUM('active', 'suspended', 'trial', 'expired')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "companyName" character varying, "taxNumber" character varying, "address" character varying, "phone" character varying, "email" character varying, "website" character varying, "currency" character varying(3) DEFAULT 'TRY', "taxOffice" character varying, "mersisNumber" character varying, "kepAddress" character varying, "tradeRegistryNumber" character varying, "siretNumber" character varying, "sirenNumber" character varying, "apeCode" character varying, "tvaNumber" character varying, "rcsNumber" character varying, "companyType" character varying, "capitalSocial" character varying, "latePaymentInterest" character varying, "fixedRecoveryFee" character varying, "steuernummer" character varying, "umsatzsteuerID" character varying, "handelsregisternummer" character varying, "geschaeftsfuehrer" character varying, "einNumber" character varying, "taxId" character varying, "salesTaxPermitNumber" character varying, "businessLicenseNumber" character varying, "stateOfIncorporation" character varying, "subscriptionPlan" "tenants_subscriptionplan_enum" NOT NULL DEFAULT 'free', "status" "tenants_status_enum" NOT NULL DEFAULT 'trial', "subscriptionExpiresAt" TIMESTAMP, "cancelAtPeriodEnd" boolean NOT NULL DEFAULT false, "stripeCustomerId" character varying(255), "stripeSubscriptionId" character varying(255), "billingInterval" character varying(16), "maxUsers" integer NOT NULL DEFAULT '5', "downgradePendingUntil" TIMESTAMP, "requiredUserReduction" integer, "settings" text, "features" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_32731f181236a46182a38c992a8" UNIQUE ("name"), CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id")); COMMENT ON COLUMN "tenants"."website" IS 'Website URL'; COMMENT ON COLUMN "tenants"."currency" IS 'Currency (TRY|USD|EUR|GBP)'; COMMENT ON COLUMN "tenants"."taxOffice" IS 'Vergi Dairesi'; COMMENT ON COLUMN "tenants"."mersisNumber" IS 'Mersis Numarası'; COMMENT ON COLUMN "tenants"."kepAddress" IS 'KEP Adresi (e-fatura)'; COMMENT ON COLUMN "tenants"."tradeRegistryNumber" IS 'Ticaret Sicil No'; COMMENT ON COLUMN "tenants"."siretNumber" IS 'SIRET Numarası (14 haneli)'; COMMENT ON COLUMN "tenants"."sirenNumber" IS 'SIREN Numarası (9 haneli)'; COMMENT ON COLUMN "tenants"."apeCode" IS 'APE/NAF Kodu (ana faaliyet)'; COMMENT ON COLUMN "tenants"."tvaNumber" IS 'TVA Numarası (FR + 11 hane)'; COMMENT ON COLUMN "tenants"."rcsNumber" IS 'RCS Numarası (Ticaret Sicil)'; COMMENT ON COLUMN "tenants"."companyType" IS 'Forme juridique / Şirket türü (SAS/SARL/EI vb.)'; COMMENT ON COLUMN "tenants"."capitalSocial" IS 'Capital social'; COMMENT ON COLUMN "tenants"."latePaymentInterest" IS 'Gecikme faizi/cezası (FR payment terms)'; COMMENT ON COLUMN "tenants"."fixedRecoveryFee" IS 'Tahsilat masrafı sabiti (FR fixed recovery fee)'; COMMENT ON COLUMN "tenants"."steuernummer" IS 'Steuernummer (Vergi Numarası)'; COMMENT ON COLUMN "tenants"."umsatzsteuerID" IS 'Umsatzsteuer-ID (DE + 9 hane)'; COMMENT ON COLUMN "tenants"."handelsregisternummer" IS 'Handelsregisternummer (Ticaret Sicil)'; COMMENT ON COLUMN "tenants"."geschaeftsfuehrer" IS 'Geschäftsführer (Genel Müdür)'; COMMENT ON COLUMN "tenants"."einNumber" IS 'EIN (Employer Identification Number)'; COMMENT ON COLUMN "tenants"."taxId" IS 'Tax ID Numarası'; COMMENT ON COLUMN "tenants"."salesTaxPermitNumber" IS 'Sales Tax Permit / Reseller Permit / State Tax Registration No'; COMMENT ON COLUMN "tenants"."businessLicenseNumber" IS 'Business License Number'; COMMENT ON COLUMN "tenants"."stateOfIncorporation" IS 'State of Incorporation'; COMMENT ON COLUMN "tenants"."billingInterval" IS 'billing interval: month|year'; COMMENT ON COLUMN "tenants"."downgradePendingUntil" IS 'Plan düşürme için son tarih'; COMMENT ON COLUMN "tenants"."requiredUserReduction" IS 'Plan düşürmede pasifleştirilmesi gereken kullanıcı sayısı'`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying, "phone" character varying, "address" text, "taxNumber" character varying, "company" character varying, "balance" numeric(15,2) NOT NULL DEFAULT '0', "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying(255), "updatedById" uuid, "updatedByName" character varying(255), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "site_settings" ("id" SERIAL NOT NULL, "defaultMetaTitle" character varying(255), "defaultMetaDescription" text, "defaultOgImageUrl" character varying(500), "canonicalBaseUrl" character varying(255), "enableIndexing" boolean NOT NULL DEFAULT true, "googleAnalyticsId" character varying(100), "googleTagManagerId" character varying(100), "pinterestTagId" character varying(100), "metaPixelId" character varying(100), "linkedinInsightTagId" character varying(100), "customHeadHtml" text, "customBodyStartHtml" text, "customBodyEndHtml" text, "announcementEnabled" boolean NOT NULL DEFAULT false, "announcementMessage" text, "announcementType" character varying(20) NOT NULL DEFAULT 'info', "maintenanceModeEnabled" boolean NOT NULL DEFAULT false, "maintenanceMessage" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e4290e8371a166d7e066d131f6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying, "phone" character varying, "address" text, "taxNumber" character varying, "siretNumber" character varying, "company" character varying, "balance" numeric(15,2) NOT NULL DEFAULT '0', "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying(255), "updatedById" uuid, "updatedByName" character varying(255), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id")); COMMENT ON COLUMN "customers"."siretNumber" IS 'SIRET Numarası (FR, 14 haneli)'`);
        await queryRunner.query(`CREATE TYPE "sales_status_enum" AS ENUM('created', 'invoiced', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "saleNumber" character varying(32) NOT NULL, "tenantId" uuid NOT NULL, "customerId" uuid, "saleDate" date NOT NULL, "subtotal" numeric(10,2) NOT NULL, "taxAmount" numeric(10,2) NOT NULL DEFAULT '0', "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL, "status" "sales_status_enum" NOT NULL DEFAULT 'created', "sourceQuoteId" character varying, "invoiceId" uuid, "items" jsonb, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying(255), "updatedById" uuid, "updatedByName" character varying(255), CONSTRAINT "UQ_e96ec22f56c541a81549f653f1f" UNIQUE ("tenantId", "saleNumber"), CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "description" text, "price" numeric(15,2) NOT NULL, "cost" numeric(15,2), "stock" numeric(10,2) NOT NULL DEFAULT '0', "minStock" numeric(10,2) NOT NULL DEFAULT '0', "unit" character varying NOT NULL DEFAULT 'pieces', "category" character varying, "barcode" character varying, "taxRate" numeric(5,2) NOT NULL DEFAULT '0', "categoryTaxRateOverride" numeric(5,2), "isActive" boolean NOT NULL DEFAULT true, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying(255), "updatedById" uuid, "updatedByName" character varying(255), CONSTRAINT "UQ_da48ca8bc452cea82db83867d9d" UNIQUE ("tenantId", "code"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "quotes_status_enum" AS ENUM('draft', 'sent', 'viewed', 'accepted', 'declined', 'expired')`);
        await queryRunner.query(`CREATE TABLE "quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "publicId" uuid NOT NULL, "publicLocale" character varying(8), "quoteNumber" character varying(32) NOT NULL, "tenantId" uuid NOT NULL, "customerId" uuid, "customerName" character varying(255), "issueDate" date NOT NULL, "validUntil" date, "currency" character varying(3) NOT NULL DEFAULT 'TRY', "total" numeric(12,2) NOT NULL DEFAULT '0', "status" "quotes_status_enum" NOT NULL DEFAULT 'draft', "items" jsonb, "scopeOfWorkHtml" text, "version" integer NOT NULL DEFAULT '1', "revisions" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying(255), "updatedById" uuid, "updatedByName" character varying(255), CONSTRAINT "UQ_44c47211dcf155fd7da2909c71e" UNIQUE ("publicId"), CONSTRAINT "UQ_a3cfb26a07c0ac65bd019e9bc50" UNIQUE ("quoteNumber"), CONSTRAINT "PK_99a0e8bcbcd8719d3a41f23c263" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "taxRate" numeric(5,2) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "parentId" character varying, "isProtected" boolean NOT NULL DEFAULT false, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "invoices_status_enum" AS ENUM('draft', 'sent', 'paid', 'overdue', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceNumber" character varying NOT NULL, "tenantId" uuid NOT NULL, "customerId" uuid, "issueDate" date NOT NULL, "dueDate" date NOT NULL, "subtotal" numeric(10,2) NOT NULL, "taxAmount" numeric(10,2) NOT NULL DEFAULT '0', "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL, "status" "invoices_status_enum" NOT NULL DEFAULT 'draft', "notes" text, "saleId" character varying, "type" character varying, "refundedInvoiceId" uuid, "items" jsonb, "is_voided" boolean NOT NULL DEFAULT false, "void_reason" text, "voided_at" TIMESTAMP, "voided_by" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying(255), "updatedById" uuid, "updatedByName" character varying(255), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fiscal_periods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "name" character varying NOT NULL, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "isLocked" boolean NOT NULL DEFAULT false, "lockedAt" TIMESTAMP, "lockedBy" uuid, "lockReason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9bb1e4e84a0d820b943e116888d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "expenses_category_enum" AS ENUM('other', 'rent', 'utilities', 'salaries', 'personnel', 'supplies', 'equipment', 'marketing', 'travel', 'insurance', 'taxes')`);
        await queryRunner.query(`CREATE TYPE "expenses_status_enum" AS ENUM('pending', 'approved', 'paid', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expenseNumber" character varying NOT NULL, "tenantId" uuid NOT NULL, "supplierId" uuid, "description" character varying NOT NULL, "expenseDate" date NOT NULL, "amount" numeric(10,2) NOT NULL, "category" "expenses_category_enum" NOT NULL DEFAULT 'other', "status" "expenses_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "receiptUrl" character varying, "is_voided" boolean NOT NULL DEFAULT false, "void_reason" text, "voided_at" TIMESTAMP, "voided_by" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying(255), "updatedById" uuid, "updatedByName" character varying(255), CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_suppression" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(320) NOT NULL, "reason" character varying(50), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7c01fd4660a34be4ff82d235f72" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_email_suppression_email" ON "email_suppression" ("email") `);
        await queryRunner.query(`CREATE TABLE "email_outbox" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "to" character varying(320) NOT NULL, "subject" character varying(255) NOT NULL, "provider" character varying(32) NOT NULL, "success" boolean NOT NULL DEFAULT false, "messageId" character varying(64), "correlationId" character varying(64), "userId" character varying(64), "tenantId" character varying(64), "tokenId" character varying(64), "type" character varying(32), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b6fbfc201f705fbf1ac87bd7197" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_648db1d4551b4ed132beebbf30" ON "email_outbox" ("to") `);
        await queryRunner.query(`CREATE TYPE "blog_posts_status_enum" AS ENUM('draft', 'published')`);
        await queryRunner.query(`CREATE TABLE "blog_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying(200) NOT NULL, "title" character varying(255) NOT NULL, "excerpt" text, "contentHtml" text NOT NULL, "contentMarkdown" text, "metaTitle" character varying(255), "metaDescription" text, "canonicalUrl" character varying(500), "ogImageUrl" character varying(500), "keywords" character varying(1000), "noIndex" boolean NOT NULL DEFAULT false, "jsonLd" text, "translations" text, "status" "blog_posts_status_enum" NOT NULL DEFAULT 'draft', "publishedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd2add25eac93daefc93da9d387" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b2818a2c45c3edb9991b1c7a5" ON "blog_posts" ("slug") `);
        await queryRunner.query(`CREATE TABLE "bank_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "name" character varying(150) NOT NULL, "iban" character varying(34) NOT NULL, "bankName" character varying(100), "currency" character varying(3) NOT NULL DEFAULT 'TRY', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c872de764f2038224a013ff25ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tokenHash" character varying(128) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "usedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "ip" character varying(45), "ua" text, CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_prt_user_id" ON "password_reset_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_prt_expires_at" ON "password_reset_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE TABLE "email_verification_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tokenHash" character varying(128) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "usedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "ip" character varying(45), "ua" text, CONSTRAINT "PK_417a095bbed21c2369a6a01ab9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_evt_user_id" ON "email_verification_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_evt_expires_at" ON "email_verification_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE TABLE "admin_config" ("id" SERIAL NOT NULL, "username" character varying(100) NOT NULL, "passwordHash" character varying(255) NOT NULL, "twoFactorEnabled" boolean NOT NULL DEFAULT false, "twoFactorSecret" character varying(255), "recoveryCodes" jsonb, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c486270cca36cc6c0ee6cf65f74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "audit_log_action_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE')`);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "tenantId" uuid NOT NULL, "entity" character varying(100) NOT NULL, "entityId" uuid, "action" "audit_log_action_enum" NOT NULL, "diff" jsonb, "ip" character varying(45), "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "FK_5652c2c6b066835b6c500d0d83f" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_members" ADD CONSTRAINT "FK_e826222ad017663c6db1a45a4f1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_9e65b4b3671b77f577afc2a71f1" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_c58f7e88c286e5e3478960a998b" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_b4287ea594fdd71f5579943dde1" FOREIGN KEY ("currentOrgId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_dd5cd678c4e94ddb93a224e7116" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_e4d10e6df143ef83689f4f96c1b" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_a514a784909249fe9da16b81d37" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_37c1a605468d156e6a8f78f1dc5" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_aa88a28eac26e514147fc7d2039" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_5ecf24c76197e0f9b4fe1741bb1" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_37606c7b1560c6be428c7a48959" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_3a92cf6add00043cef9833db1cd" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_579a13a0f8d438c6f5a0d732556" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_0e2de179c892d8fed41ae8d1e19" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_6804855ba1a19523ea57e0769b4" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_de1043dff8f68e83a20480b00f7" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_3aa627ab6766f571d413ca8cbde" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_6035d30fc2417ed19972a7ce028" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_ccf1feb9e280240bb05dc0aed2a" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_3c3c38f2fc5c43fb8e8440ca012" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_7f3f5694ac63e8723d9c94110af" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_511a82b0123c941ba3f49ab025e" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_89c82485e364081f457b210120d" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1df049f8943c6be0c1115541efb" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_7665522bed89854413b7d6cfe71" FOREIGN KEY ("refundedInvoiceId") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_e9682eb7c1839bb55c6b77e5b81" FOREIGN KEY ("voided_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_dc9c84f58ab53b5c844c276e435" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_bd029129da2a96c7da74c0a2eb7" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fiscal_periods" ADD CONSTRAINT "FK_a2c50d3c70519722b5b74febd60" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fiscal_periods" ADD CONSTRAINT "FK_030a71ef0a0292a218408aed44c" FOREIGN KEY ("lockedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_f754faa125acaf008866b6635bc" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_cb04770a68c157a22fa42cc0506" FOREIGN KEY ("supplierId") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_6103e35625584836bed4dab6b92" FOREIGN KEY ("voided_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_4f3e45915b1db0536a90400b419" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_6f63b01ea8905570f2b9c98cc31" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD CONSTRAINT "FK_56cb500b41e924b1fadc5051d5d" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_10f285d038feb767bf7c2da14b3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_2621409ebc295c5da7ff3e41396" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_4167b21288ab6e16239cb1d5016" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        throw new Error("The initial customer schema baseline cannot be reverted safely");
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_4167b21288ab6e16239cb1d5016"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_2621409ebc295c5da7ff3e41396"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_10f285d038feb767bf7c2da14b3"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP CONSTRAINT "FK_56cb500b41e924b1fadc5051d5d"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_6f63b01ea8905570f2b9c98cc31"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_4f3e45915b1db0536a90400b419"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_6103e35625584836bed4dab6b92"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_cb04770a68c157a22fa42cc0506"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_f754faa125acaf008866b6635bc"`);
        await queryRunner.query(`ALTER TABLE "fiscal_periods" DROP CONSTRAINT "FK_030a71ef0a0292a218408aed44c"`);
        await queryRunner.query(`ALTER TABLE "fiscal_periods" DROP CONSTRAINT "FK_a2c50d3c70519722b5b74febd60"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_bd029129da2a96c7da74c0a2eb7"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_dc9c84f58ab53b5c844c276e435"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_e9682eb7c1839bb55c6b77e5b81"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_7665522bed89854413b7d6cfe71"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1df049f8943c6be0c1115541efb"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_89c82485e364081f457b210120d"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_511a82b0123c941ba3f49ab025e"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_7f3f5694ac63e8723d9c94110af"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_3c3c38f2fc5c43fb8e8440ca012"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_ccf1feb9e280240bb05dc0aed2a"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_6035d30fc2417ed19972a7ce028"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_3aa627ab6766f571d413ca8cbde"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_de1043dff8f68e83a20480b00f7"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_6804855ba1a19523ea57e0769b4"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_0e2de179c892d8fed41ae8d1e19"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_579a13a0f8d438c6f5a0d732556"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_3a92cf6add00043cef9833db1cd"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_37606c7b1560c6be428c7a48959"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_5ecf24c76197e0f9b4fe1741bb1"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_aa88a28eac26e514147fc7d2039"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_37c1a605468d156e6a8f78f1dc5"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_a514a784909249fe9da16b81d37"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_e4d10e6df143ef83689f4f96c1b"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_dd5cd678c4e94ddb93a224e7116"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_b4287ea594fdd71f5579943dde1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_c58f7e88c286e5e3478960a998b"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_9e65b4b3671b77f577afc2a71f1"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "FK_e826222ad017663c6db1a45a4f1"`);
        await queryRunner.query(`ALTER TABLE "organization_members" DROP CONSTRAINT "FK_5652c2c6b066835b6c500d0d83f"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP TYPE "audit_log_action_enum"`);
        await queryRunner.query(`DROP TABLE "admin_config"`);
        await queryRunner.query(`DROP INDEX "idx_evt_expires_at"`);
        await queryRunner.query(`DROP INDEX "idx_evt_user_id"`);
        await queryRunner.query(`DROP TABLE "email_verification_tokens"`);
        await queryRunner.query(`DROP INDEX "idx_prt_expires_at"`);
        await queryRunner.query(`DROP INDEX "idx_prt_user_id"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "bank_accounts"`);
        await queryRunner.query(`DROP INDEX "IDX_5b2818a2c45c3edb9991b1c7a5"`);
        await queryRunner.query(`DROP TABLE "blog_posts"`);
        await queryRunner.query(`DROP TYPE "blog_posts_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_648db1d4551b4ed132beebbf30"`);
        await queryRunner.query(`DROP TABLE "email_outbox"`);
        await queryRunner.query(`DROP INDEX "idx_email_suppression_email"`);
        await queryRunner.query(`DROP TABLE "email_suppression"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "expenses_status_enum"`);
        await queryRunner.query(`DROP TYPE "expenses_category_enum"`);
        await queryRunner.query(`DROP TABLE "fiscal_periods"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP TABLE "quotes"`);
        await queryRunner.query(`DROP TYPE "quotes_status_enum"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TYPE "sales_status_enum"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "site_settings"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "tenants_status_enum"`);
        await queryRunner.query(`DROP TYPE "tenants_subscriptionplan_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "users_role_enum"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP TYPE "organizations_plan_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_18a9a6c85f7cc6f42ebef3b318"`);
        await queryRunner.query(`DROP TABLE "invites"`);
        await queryRunner.query(`DROP TYPE "invites_role_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_e826222ad017663c6db1a45a4f"`);
        await queryRunner.query(`DROP INDEX "IDX_5652c2c6b066835b6c500d0d83"`);
        await queryRunner.query(`DROP TABLE "organization_members"`);
        await queryRunner.query(`DROP TYPE "organization_members_role_enum"`);
    }

}
